//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionGeneration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExam
    {
        public int UE_Id { get; set; }
        public int SubjectId { get; set; }
        public int QId { get; set; }
        public int Ans_Id { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
